name: Weekly Slack Groups

on:
  schedule:
    - cron: "10 0 * * FRI"  # 월요일 00:00 UTC == 월요일 09:00 한국시간
  workflow_dispatch:

jobs:
  send-groups:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python group_sender.py
